[workspace]
resolver = "2"
members = [
    "access_server",
    "common",
    "proxy_client",
    "proxy_server",
    "server",
    "tests",
]

[workspace.dependencies]
async-speed-limit = { version = "0.4", features = ["tokio"] }
bincode = "1"
bytes = "1"
metrics = "0.22"
metrics-exporter-prometheus = { version = "0.13", default-features = false }
mptcp = { git = "https://github.com/Banyc/mptcp.git", rev = "44b3d6366e6580e80f70607263ed6065b493b78f" }
openssl = "0.10"
serde = "1"
tabled = "0.15"
thiserror = "1"
tokio = "1"
tokio-util = "0.7"
tokio_chacha20 = { git = "https://github.com/Banyc/tokio_chacha20.git", rev = "6eb96a8e86a1cca71e3d7c1c1b914244afdfe9fc" }
tokio_kcp = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"
