[workspace]
resolver = "2"
members = [
    "access_server",
    "common",
    "proxy_client",
    "proxy_server",
    "server",
    "tests",
]

[workspace.dependencies]
async-speed-limit = { version = "0.4", features = ["tokio"] }
bincode = "1"
bytes = "1"
csv_logger = { git = "https://github.com/Banyc/csv_logger.git", rev = "d63ac71c4eeb55268102695b095fb6bf13b7ee8f" }
metrics = "0.22"
metrics-exporter-prometheus = { version = "0.13", default-features = false }
monitor_table = { git = "https://github.com/Banyc/monitor_table.git", rev = "f9cbe7a0e792d793adbe5627402254b0c9eee46b" }
mptcp = { git = "https://github.com/Banyc/mptcp.git", rev = "9f023f2db96fba80ae044d0101f7955975272dd5" }
openssl = "0.10"
serde = "1"
strict-num = "0.2"
table_log = { git = "https://github.com/Banyc/table_log.git", rev = "eb936cc4521dd62854a1272da6908f7d70261c2c" }
thiserror = "1"
tokio = "1"
tokio-util = "0.7"
tokio_chacha20 = { git = "https://github.com/Banyc/tokio_chacha20.git", rev = "40d2030f0ab6e7e32031e61618717d25f25e5509" }
tokio_kcp = "0.9"
tokio_throughput = { git = "https://github.com/Banyc/tokio_throughput.git", rev = "80cbf0572623762665caff07781cee3e0d97cfc7" }
tracing = "0.1"
tracing-subscriber = "0.3"
