[workspace]
resolver = "2"
members = [
    "access_server",
    "common",
    "proxy_client",
    "proxy_server",
    "server",
    "tests",
]

[workspace.dependencies]
async-speed-limit = { version = "0.4", features = ["tokio"] }
bincode = "1"
bytes = "1"
metrics = "0.22"
metrics-exporter-prometheus = { version = "0.13", default-features = false }
monitor_table = { git = "https://github.com/Banyc/monitor_table.git", rev = "cac3c81cab8b7ba39e76147f0744c7509cb9d642" }
mptcp = { git = "https://github.com/Banyc/mptcp.git", rev = "9f023f2db96fba80ae044d0101f7955975272dd5" }
openssl = "0.10"
serde = "1"
thiserror = "1"
tokio = "1"
tokio-util = "0.7"
tokio_chacha20 = { git = "https://github.com/Banyc/tokio_chacha20.git", rev = "40d2030f0ab6e7e32031e61618717d25f25e5509" }
tokio_kcp = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"
