[package]
name = "access_server"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-speed-limit = { git = "https://github.com/tikv/async-speed-limit.git", rev = "36d79e063144cf0cdfc258c9e127c84f10a53b57", features = ["tokio"] }
async-trait = "0.1.71"
bytes = "1.4.0"
common = { path = "../common" }
http-body-util = "=0.1.0-rc.2"
hyper = { version = "=1.0.0-rc.3", features = ["full"] }
proxy_client = { path = "../proxy_client" }
serde = { version = "1.0.171", features = ["derive"] }
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
