[package]
name = "access_server"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-speed-limit = { version = "0.4.1", features = ["tokio"] }
async-trait = "0.1.73"
bytes = "1.5.0"
common = { path = "../common" }
http-body-util = "0.1.0"
hyper = { version = "1.0.0", features = ["full"] }
pin-project-lite = "0.2.13"
proxy_client = { path = "../proxy_client" }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
tokio-util = "0.7.9"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
