[package]
name = "access_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy_client = { path = "../proxy_client" }
get_config = "0.1.1"
common = { path = "../common" }
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
async-trait = "0.1.68"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
bytes = "1.4.0"
http-body-util = "0.1.0-rc.2"
thiserror = "1.0.40"
