[[tcp_servers]]
listen_addr = ""
destination = { address = "", stream_type = "tcp" }
# payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# stream_pool = [{ address = "", stream_typ = "" }]
[[tcp_servers.proxy_configs]]
address = ""
xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

[[udp_servers]]
listen_addr = ""
destination = { address = "" }
[[udp_servers.proxy_configs]]
address = ""
xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

[[http_servers]]
listen_addr = ""
# payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# stream_pool = [{ address = "", stream_typ = "" }]
[[http_servers.proxy_configs]]
address = ""
xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
