[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
access_server = { path = "../access_server" }
get_config = "0.1.1"
proxy_server = { path = "../proxy_server" }
serde = { version = "1.0.163", features = ["derive"] }
tokio = { version = "1.28.2", features = ["full"] }
tracing-subscriber = "0.3.17"
