[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
access_server = { path = "../access_server" }
async-trait = "0.1.73"
clap = { version = "4.4.2", features = ["derive"] }
common = { path = "../common" }
file_watcher_tokio = "0.2.0"
notify = "6.1.1"
proxy_server = { path = "../proxy_server" }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
toml = "0.7.7"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
