[access_server]
# stream_pool = ["tcp://"]
# [access_server.stream_proxy_tables]
# "default" = { chains = [
#     { weight = 1, chain = [
#         { address = "tcp://", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
#     ],                        payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
# ], trace_rtt = false }
# [access_server.udp_proxy_tables]
# "default" = { chains = [
#     { weight = 1, chain = [
#         { address = "", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
#     ] },
# ], trace_rtt = false }
# [access_server.filters]
# "default" = [
#     "localhost",
#     # { match = "", action = "block" },
# ]
# "localhost" = [
#     { match = "127\\.0\\.0\\.1:", action = "direct" },
#     { match = "[::1]:", action = "direct" },
#     { match = "localhost:", action = "direct" },
# ]

[[access_server.tcp_server]]
listen_addr = ""
destination = "tcp://"
# proxy_table = "default"
proxy_table = { chains = [
    { weight = 1, chain = [
        { address = "tcp://", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
    ],                        payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
], trace_rtt = false }
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.udp_server]]
listen_addr = ""
destination = ""
# proxy_table = "default"
proxy_table = { chains = [
    { weight = 1, chain = [
        { address = "", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
    ],                  payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
], trace_rtt = false }
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.http_server]]
listen_addr = ""
# proxy_table = "default"
proxy_table = { chains = [
    { weight = 1, chain = [
        { address = "tcp://", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
    ],                        payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
], trace_rtt = false }
# filter = "default"
filter = [
    { match = "127\\.0\\.0\\.1:", action = "direct" },
    { match = "[::1]:", action = "direct" },
    { match = "localhost:", action = "direct" },
    # { match = "", action = "block" },
]
# speed_limit = 1024.0 # 1.0 KiB/s

[[proxy_server.tcp_server]]
listen_addr = ""
header_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# stream_pool = ["tcp://"]

[[proxy_server.kcp_server]]
listen_addr = ""
header_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# stream_pool = ["tcp://"]

[[proxy_server.udp_server]]
listen_addr = ""
header_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
