[global]
stream_pool = ["tcp://proxy.example.org:80", "mptcp://proxy.example.org:81"]

[access_server.stream_proxy_tables]
"default" = { chains = [
    { weight = 1, chain = [
        { address = "tcp://proxy.example.org:80", xor_key = "base64" },
    ],                                            payload_xor_key = "base64" },
    { weight = 1, chain = [
        { address = "kcp://proxy.example.org:80", xor_key = "base64" },
    ],                                            payload_xor_key = "base64" },
    { weight = 1, chain = [
        { address = "mptcp://proxy.example.org:81", xor_key = "base64" },
    ],                                              payload_xor_key = "base64" },
], trace_rtt = false, active_chains = 3 }
[access_server.udp_proxy_tables]
"default" = { chains = [
    { weight = 1, chain = [
        { address = "proxy.example.org:80", xor_key = "base64" },
    ],                                      payload_xor_key = "base64" },
], trace_rtt = false, active_chains = 1 }
[access_server.filters]
"default" = [
    "localhost",
    # { matcher = { port = 443 }, action = "proxy" },
    # { matcher = { }, action = "block" }, # Block all
]
"localhost" = [
    { matcher = [
        { addr = "127.0.0.1" }, # IPv4
        { addr = "::1" },       # IPv6
        { addr = "localhost" }, # domain name regex
    ], action = "direct" },
]

[[access_server.tcp_server]]
listen_addr = "0.0.0.0:80"
destination = "tcp://www.example.org:80"
proxy_table = "default"                  # Or, `proxy_table = { chains = ..., trace_rtt = ..., ... }`
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.udp_server]]
listen_addr = "0.0.0.0:80"
destination = "www.example.org:80"
proxy_table = "default"            # Or, `proxy_table = { chains = ..., trace_rtt = ..., ... }`
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.http_server]]
listen_addr = "0.0.0.0:80"
proxy_table = "default"    # Or, `proxy_table = { chains = ..., trace_rtt = ..., ... }`
filter = "default"
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.socks5_tcp_server]]
listen_addr = "0.0.0.0:80"
udp_server_addr = "0.0.0.0:80"
proxy_table = "default"        # Or, `proxy_table = { chains = ..., trace_rtt = ..., ... }`
filter = "default"
# speed_limit = 1024.0 # 1.0 KiB/s
# users = [
#     { username = "", password = "" },
# ]

[[access_server.socks5_udp_server]]
listen_addr = "0.0.0.0:80"
proxy_table = "default"    # Or, `proxy_table = { chains = ..., trace_rtt = ..., ... }`
# speed_limit = 1024.0 # 1.0 KiB/s

[[proxy_server.tcp_server]]
listen_addr = "0.0.0.0:80"
header_xor_key = "base64"
# payload_xor_key = "base64"

[[proxy_server.kcp_server]]
listen_addr = "0.0.0.0:80"
header_xor_key = "base64"
# payload_xor_key = "base64"

[[proxy_server.mptcp_server]]
listen_addr = "0.0.0.0:81"
header_xor_key = "base64"
# payload_xor_key = "base64"

[[proxy_server.udp_server]]
listen_addr = "0.0.0.0:80"
header_xor_key = "base64"
# payload_xor_key = "base64"
