[access_server]
stream_pool = ["tcp://"]
[access_server.stream_proxy_tables]
"default" = { chains = [
    { weight = 1, chain = [
        { address = "tcp://", xor_key = "base64" },
    ],                        payload_xor_key = "base64" },
    { weight = 1, chain = [
        { address = "kcp://", xor_key = "base64" },
    ],                        payload_xor_key = "base64" },
], trace_rtt = false, active_chains = 1 }
[access_server.udp_proxy_tables]
"default" = { chains = [
    { weight = 1, chain = [
        { address = "", xor_key = "base64" },
    ],                  payload_xor_key = "base64" },
], trace_rtt = false, active_chains = 1 }
[access_server.filters]
"default" = [
    "localhost",
    # { matcher = { port = 443 }, action = "proxy" },
    # { matcher = { }, action = "block" }, # Block all
]
"localhost" = [
    { matcher = [
        { addr = "127.0.0.1" }, # IPv4
        { addr = "::1" },       # IPv6
        { addr = "localhost" }, # domain name regex
    ], action = "direct" },
]

[[access_server.tcp_server]]
listen_addr = ""
destination = "tcp://"
proxy_table = "default"
# proxy_table = { chains = [
#     { weight = 1, chain = [
#         { address = "tcp://", xor_key = "base64" },
#     ],                        payload_xor_key = "base64" },
# ], trace_rtt = false }
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.udp_server]]
listen_addr = ""
destination = ""
# proxy_table = "default"
proxy_table = { chains = [
    { weight = 1, chain = [
        { address = "", xor_key = "base64" },
    ],                  payload_xor_key = "base64" },
], trace_rtt = false }
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.http_server]]
listen_addr = ""
proxy_table = "default"
# proxy_table = { chains = [
#     { weight = 1, chain = [
#         { address = "tcp://", xor_key = "base64" },
#     ],                        payload_xor_key = "base64" },
# ], trace_rtt = false }
filter = "default"
# speed_limit = 1024.0 # 1.0 KiB/s

[[access_server.socks5_tcp_server]]
listen_addr = ""
udp_server_addr = ""
proxy_table = "default"
# proxy_table = { chains = [
#     { weight = 1, chain = [
#         { address = "tcp://", xor_key = "base64" },
#     ],                        payload_xor_key = "base64" },
# ], trace_rtt = false }
filter = "default"
# speed_limit = 1024.0 # 1.0 KiB/s
# users = [
#     { username = "", password = "" },
# ]

[[access_server.socks5_udp_server]]
listen_addr = ""
proxy_table = "default"
# proxy_table = { chains = [
#     { weight = 1, chain = [
#         { address = "", xor_key = "base64" },
#     ],                  payload_xor_key = "base64" },
# ], trace_rtt = false }
# speed_limit = 1024.0 # 1.0 KiB/s

[[proxy_server.tcp_server]]
listen_addr = ""
header_xor_key = "base64"
# payload_xor_key = "base64"
# stream_pool = ["tcp://"]

[[proxy_server.kcp_server]]
listen_addr = ""
header_xor_key = "base64"
# payload_xor_key = "base64"
# stream_pool = ["tcp://"]

[[proxy_server.udp_server]]
listen_addr = ""
header_xor_key = "base64"
# payload_xor_key = "base64"
