[[access_server.tcp_server]]
listen_addr = ""
destination = "tcp://"
# stream_pool = ["tcp://"]
proxy_table = [
    { weight = 1, chain = [
        { address = "tcp://", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
    ], payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
]

[[access_server.udp_server]]
listen_addr = ""
destination = ""
proxy_table = [
    { weight = 1, chain = [
        { address = "", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
    ] },
]

[[access_server.http_server]]
listen_addr = ""
# stream_pool = ["tcp://"]
proxy_table = [
    { weight = 1, chain = [
        { address = "tcp://", xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
    ], payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
]
filter = [
    { match = "127\\.0\\.0\\.1:", action = "direct" },
    { match = "[::1]:", action = "direct" },
    { match = "localhost:", action = "direct" },
    # { match = "", action = "block" },
]

[[proxy_server.tcp_server]]
listen_addr = ""
header_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# stream_pool = ["tcp://"]

[[proxy_server.kcp_server]]
listen_addr = ""
header_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# payload_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# stream_pool = ["tcp://"]

[[proxy_server.udp_server]]
listen_addr = ""
header_xor_key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
