[package]
name = "proxy_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-speed-limit = { version = "0.4.1", features = ["tokio"] }
async-trait = "0.1.73"
bincode = "1.3.3"
common = { path = "../common" }
mptcp = { git = "https://github.com/Banyc/mptcp.git", rev = "428b14bfcf176122ea74031d6f8c3f5572bfc5f6" }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
tokio_kcp = "0.9.6"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
