[package]
name = "proxy_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-speed-limit = { git = "https://github.com/tikv/async-speed-limit.git", rev = "36d79e063144cf0cdfc258c9e127c84f10a53b57", features = ["tokio"] }
async-trait = "0.1.71"
bincode = "1.3.3"
common = { path = "../common" }
quinn = "0.10.1"
serde = { version = "1.0.171", features = ["derive"] }
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tokio_kcp = { git = "https://github.com/Matrix-Zhang/tokio_kcp.git", rev = "89979a898c8ae2c69d83746f6af1f78a96443685" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
