[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-speed-limit = { version = "0.4.1", features = ["tokio"] }
async-trait = "0.1.73"
base64 = "0.21.2"
bincode = "1.3.3"
bytesize = "1.2.0"
duplicate = "1.0.0"
futures-core = "0.3.28"
lazy_static = "1.4.0"
lru = "0.11.0"
pin-project-lite = "0.2.12"
# quinn = "0.10.1"
rand = "0.8.5"
rayon = "1.7.0"
regex = "1.9.3"
serde = { version = "1.0.183", features = ["derive",  "rc"] }
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full"] }
tokio-io-timeout = "1.2.0"
tokio_kcp = { git = "https://github.com/Matrix-Zhang/tokio_kcp.git", rev = "89979a898c8ae2c69d83746f6af1f78a96443685" }
tracing = "0.1.37"

[dev-dependencies]
rand = "0.8.5"
