[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-speed-limit = { git = "https://github.com/tikv/async-speed-limit.git", rev = "36d79e063144cf0cdfc258c9e127c84f10a53b57", features = ["tokio"] }
async-trait = "0.1.71"
bincode = "1.3.3"
bytesize = "1.2.0"
duplicate = "1.0.0"
futures-core = "0.3.28"
lazy_static = "1.4.0"
pin-project-lite = "0.2.10"
quinn = "0.10.1"
rand = "0.8.5"
regex = "1.9.1"
serde = { version = "1.0.171", features = ["derive",  "rc"] }
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tokio-io-timeout = "1.2.0"
tokio_kcp = { git = "https://github.com/Matrix-Zhang/tokio_kcp.git", rev = "89979a898c8ae2c69d83746f6af1f78a96443685" }
tracing = "0.1.37"

[dev-dependencies]
rand = "0.8.5"
