[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
bincode = "1.3.3"
bytesize = "1.2.0"
duplicate = "1.0.0"
serde = { version = "1.0.160", features = ["derive",  "rc"] }
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
tracing = "0.1.37"

[dev-dependencies]
rand = "0.8.5"
