[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.6.0"
async-speed-limit = { version = "0.4.1", features = ["tokio"] }
base64 = "0.21.4"
bincode = "1.3.3"
bytes = "1.5.0"
bytesize = "1.3.0"
duplicate = "1.0.0"
enum-map = "2.6.3"
futures-core = "0.3.28"
lockfree-object-pool = "0.1.4"
lru = "0.12.0"
metrics = { workspace = true }
mptcp = { workspace = true }
once_cell = "1.18.0"
pin-project-lite = "0.2.13"
# quinn = "0.10.1"
rand = "0.8.5"
rayon = "1.8.0"
regex = "1.10.2"
scopeguard = "1.2.0"
serde = { workspace = true, features = ["derive",  "rc"] }
slotmap = "1.0.6"
tabled = { workspace = true }
thiserror = "1.0.50"
tokio = { workspace = true, features = ["full"] }
tokio-io-timeout = "1.2.0"
tokio-util = { workspace = true }
tokio_kcp = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rand = "0.8.5"
serde_json = "1.0.107"
